apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: hacktoberfestflask
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: ronaldpineda/my-flask-app
        name: my-app